# Generated by Django 3.2.8 on 2021-10-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_img', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stars', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('addres', models.CharField(max_length=255)),
                ('url_img', models.URLField(max_length=255)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.city')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services_hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_hotel', to='hotels.hotel')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.services')),
            ],
        ),
        migrations.CreateModel(
            name='Photos_outside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img', models.URLField(max_length=255)),
                ('name_img', models.CharField(max_length=50)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_outside', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Photos_inside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img', models.URLField(max_length=255)),
                ('name_img', models.CharField(max_length=50)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_inside', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=400)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotels.hotel')),
            ],
        ),
    ]
