# Generated by Django 3.1.12 on 2021-10-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stars', models.PositiveIntegerField()),
                ('main_1', models.URLField(max_length=250)),
                ('main_2', models.URLField(max_length=250)),
                ('main_3', models.URLField(max_length=250)),
                ('main_4', models.URLField(max_length=250)),
                ('services', models.CharField(max_length=200)),
                ('hab_1', models.URLField(max_length=250)),
                ('hab_2', models.URLField(max_length=250)),
                ('hab_3', models.URLField(max_length=250)),
                ('hab_4', models.URLField(max_length=250)),
                ('hab_5', models.URLField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='National_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('review_text', models.CharField(max_length=500)),
                ('review_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotels.national_city'),
        ),
    ]
